<template>
    <div>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
    </div>
</template>

<script>
export default {
  data () {
    return {}
  },
  created () {
    this.$axios('Statistics/statisticsEntrance', {type: ['car_info', 'finance', 'finance_income']})
  }
}
</script>
